# Generated by Django 4.1.7 on 2023-03-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_image_rename_forename_athlet_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlet',
            name='category',
            field=models.CharField(choices=[('duathlon', 'Duathlon'), ('duathlon_triathlon', 'Duathlon/Triathlon'), ('triathlon', 'Triathlon'), ('cycling', 'Cycling')], default='duathlon_triathlon', max_length=20),
        ),
    ]
