# Generated by Django 4.1.7 on 2023-04-02 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_athlet_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlet',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='AthletImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('athlet', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.athlet')),
            ],
        ),
    ]
