# Generated by Django 4.1.7 on 2023-04-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_athlet_images_athletimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlet',
            old_name='images',
            new_name='image',
        ),
    ]
