# Generated by Django 4.1.4 on 2023-04-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_image_athlet_hero_aboutsection_text_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerstage',
            name='text_de',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
