# Generated by Django 4.1.4 on 2023-04-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_careerstage_text_de'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='titel_de',
            new_name='title_de',
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='text_de',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title_de',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
