# Generated by Django 4.1.4 on 2023-04-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_titel_de_page_title_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title_de',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_de',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_de',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
