# Generated by Django 4.1.4 on 2023-04-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_contactdata_phone_contactdata_phone_ch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletimage',
            name='image',
            field=models.ImageField(upload_to='uploads/athlets/'),
        ),
    ]
