# Generated by Django 4.1.4 on 2023-04-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_athletimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlet',
            name='hero',
            field=models.ImageField(blank=True, upload_to='uploads/athlets/'),
        ),
    ]
