# Generated by Django 4.1.4 on 2023-04-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_athlet_position_alter_page_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/athlets/')),
                ('image_alt', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='athlet',
            name='position',
            field=models.CharField(blank=True, choices=[('center', 'Center'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='position',
            field=models.CharField(blank=True, choices=[('center', 'Center'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=20, null=True),
        ),
    ]
