# Generated by Django 4.1.4 on 2023-04-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_myimage_alter_athlet_position_alter_page_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimage',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
