# Generated by Django 4.1.4 on 2023-04-16 10:03

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_myimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#DB2828', image_field=None, max_length=18, samples=[('#DB2828', 'red'), ('#fff12a', 'yellow')])),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.image'),
        ),
        migrations.AddField(
            model_name='athletimage',
            name='image_alt',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='athletimage',
            name='position',
            field=models.CharField(choices=[('center', 'Center'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=20),
        ),
        migrations.AddField(
            model_name='athletimage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='athletimage',
            name='subtitle_de',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='myimage',
            name='position',
            field=models.CharField(choices=[('center', 'Center'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=20),
        ),
        migrations.AddField(
            model_name='myimage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='myimage',
            name='subtitle_de',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='position',
            field=models.CharField(choices=[('center', 'Center'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle_de',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='athlet',
            name='position',
            field=models.CharField(choices=[('center', 'Center'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About me'), ('coaching', 'Coaching'), ('athlets', 'Athlets'), ('athlet', 'Single Athlet'), ('blog', 'Blog'), ('contact', 'Contact'), ('impressum', 'Impressum'), ('legal', 'Data protection')], default='home', max_length=20),
        ),
        migrations.AlterField(
            model_name='page',
            name='position',
            field=models.CharField(choices=[('center', 'Center'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_de',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.postcategory'),
        ),
    ]
