# Generated by Django 4.1.4 on 2023-04-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_postcategory_posttag_alter_posttag_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='tag',
        ),
    ]
