# Generated by Django 4.1.4 on 2023-04-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_post_link_post_link_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_text_de',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
