# Generated by Django 5.1.3 on 2024-11-29 11:12

import colorfield.fields
import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_socialmedia_options_alter_aboutsection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text_de',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content german'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_de',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content german'),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='color',
            field=colorfield.fields.ColorField(default='#DB2828', image_field=None, max_length=25, samples=[('#DB2828', 'red'), ('#fff12a', 'yellow')]),
        ),
        migrations.DeleteModel(
            name='AboutSection',
        ),
    ]
