# Generated by Django 5.1.3 on 2024-11-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_page_text_alter_page_text_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerstage',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='careerstage',
            name='title_de',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='careerstage',
            name='text',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
