# Generated by Django 5.1.3 on 2024-11-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_careerstage_title_careerstage_title_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimage',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
