# Generated by Django 5.1.3 on 2024-11-29 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_myimage_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myimage',
            options={'ordering': ['ordering']},
        ),
        migrations.RenameField(
            model_name='myimage',
            old_name='sequence',
            new_name='ordering',
        ),
    ]
