# Generated by Django 5.1.3 on 2024-11-29 23:38

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_myimage_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='link_text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='link_text_de',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subtitle_de',
        ),
        migrations.AlterField(
            model_name='page',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About me'), ('coaching', 'Coaching'), ('athletes', 'Athletes'), ('blog', 'Blog'), ('contact', 'Contact'), ('impressum', 'Impressum'), ('legal', 'Data protection')], default='home', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.posttag'),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='AthletImage',
            new_name='AthleteImage',
        ),
        migrations.RenameModel(
            old_name='Athlet',
            new_name='Athlete',
        ),

    ]
