# Generated by Django 5.1.3 on 2024-11-29 23:41

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_athlete_delete_athlet_remove_athleteimage_athlet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleteimage',
            old_name='athlet',
            new_name='athlete',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='hero',
        ),
        migrations.AddField(
            model_name='athlete',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='content_de',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content german'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='hero_img',
            field=models.ImageField(blank=True, upload_to='uploads/athlets/', verbose_name='Hero Image'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='position',
            field=models.CharField(choices=[('center', 'Center'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=20, verbose_name='Hero Position'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='published',
            field=models.BooleanField(default=True, help_text='If checked, this athlete will be published on the website.'),
        ),
    ]
